version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-flask-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: digital_college
    volumes:
      - ./sql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask:
    build: .
    container_name: flask-container
    restart: always
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: digital_college
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    command: >
      /bin/sh -c "
      flask db upgrade &&
      flask run --host=0.0.0.0 --port=5000"
