version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-flask-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: digital_college
    volumes:
      - $(pwd)\sql_data:/var/lib/mysql  # Volume relatif
    ports:
      - "3306:3306"
