"""First Migration

Revision ID: 464fc6743b6d
Revises: 
Create Date: 2024-12-04 16:03:37.155477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464fc6743b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retour_formation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_bootcamp', sa.String(length=150), nullable=False),
    sa.Column('formation', sa.String(length=150), nullable=False),
    sa.Column('priorite_retour', sa.String(length=50), nullable=False),
    sa.Column('type_retour', sa.String(length=150), nullable=False),
    sa.Column('date_retour', sa.Date(), nullable=False),
    sa.Column('evaluation', sa.Integer(), nullable=False),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('fichier_joint', sa.String(length=250), nullable=True),
    sa.Column('donnees_acceptees', sa.Boolean(), nullable=False),
    sa.Column('delete_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retour_formation')
    # ### end Alembic commands ###
